name: CI Workflow

on:
  push:
    branches:
      - main
      - release
      - feat/tests
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    

    env:
      FULL_NAME: "Медолазов Андрей Андреевич"
      GROUP_NUMBER: "M3110"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Output personal information
        run: |
          echo "ФИО: ${{ env.FULL_NAME }}"
          echo "Номер группы: ${{ env.GROUP_NUMBER }}"
          echo "Ник на GitHub: ${{ github.actor }}"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run tests
        run: |
          python3 -m unittest discover -s tests

      - name: Check code style
        run: |
          python3 -m pip install --upgrade pip
          pip install black
          black .
          black --check .
